# Generated by Django 3.2.4 on 2021-06-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0003_trabajo_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajo',
            old_name='Materiales',
            new_name='materiales',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
