# Generated by Django 3.2.4 on 2021-06-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0005_trabajo_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='usuario',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
