# Generated by Django 3.2.4 on 2021-06-20 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0006_trabajo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('auto_inc', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='galerias')),
                ('Trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rayoMakween.trabajo')),
            ],
        ),
    ]
