# Generated by Django 3.2.4 on 2021-06-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0008_auto_20210622_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('fono', models.CharField(max_length=10)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='imagen',
            field=models.ImageField(default='trabajos/defecto.jpg', upload_to='trabajos'),
        ),
    ]
