# Generated by Django 3.2.4 on 2021-06-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0009_auto_20210626_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='id',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
