# Generated by Django 3.2.4 on 2021-06-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0010_auto_20210626_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='fono',
            new_name='telefono',
        ),
    ]
